### PR TITLE
cache: add Clear, fix NewItem/NewSet, fix typos, add MaxIdleAge

### LINKED ISSUE #4: Reset item expiry upon access / LRU option
**Description:**

I'm currently using the twmb/go-cache library to cache Kafka clients with the following settings:

```go
cacheSettings := []cache.Opt{
    cache.MaxAge(30 * time.Second),
    cache.MaxErrorAge(time.Second),
    cache.AutoCleanInterval(15 * time.Second),
}

return &KafkaClientProvider{
    clientCache: cache.New[string, *kgo.Client](cacheSettings...),
}
```

The cache works well, but I'm missing a feature: the ability to reset the expiry timer (in my case, MaxAge of 30 seconds) whenever an entry is retrieved. The current behavior is that entries become stale (eligible for cleanup/eviction) based on the initial time they were set, regardless of how often they're accessed.

**Problem:**

In my use case, I want the cached Kafka clients to only be evicted if they haven't been accessed for the duration specified by `MaxAge`. The current setup evicts items based on their initial creation time, which means even frequently accessed items are evicted after 30 seconds.

**Proposal:**

Introduce a new cache option, which can be added to reset the timer for an entry upon access/retrieval. This would basically allow a LRU cache. Usage could look like this:

```go
  // A configurable function where users specify what the new maxAge or maxErrorAge should be.
  cache.RefreshExpiryOnAccess(maxAge, maxErrorAge time.Duration)
```

### PR DESCRIPTION
**Pull request by twmb**
Add Clear() to Cache, Item, and Set, matching sync.Map.Clear (added in Go 1.23). Cache.Clear resets internal state under the lock; Item.Clear and Set.Clear delegate.

Fix NewItem and NewSet to delegate to New, which was previously skipped — this caused missing pd allocation and auto-clean goroutine setup.

Fix "the the" typo in CompareAndDelete docs, and add explicit parens to clarify operator precedence in ent.get.

Update test infrastructure (mapInterface, RWMutexMap, CacheMap, and quickcheck ops) for Clear. Update README mapping table.

---

MaxIdleAge resets an entry's expiry to now+age on each successful
Get/TryGet hit (no error), keeping entries alive while actively
accessed and expiring them after a period of inactivity. Range and
Delete do not extend. When used without MaxAge, MaxIdleAge serves
as the initial TTL.

Closes https://github.com/twmb/go-cache/issues/4.

### CODE REVIEW

File: cache/cache.go [hunk 1]
```diff
@@ -160,6 +164,14 @@ func MaxErrorAge(age time.Duration) Opt {
 	return opt{fn: func(c *cfg) { c.maxErrAge, c.errAgeSet = age, true }}
 }
 
+// MaxIdleAge opts in to extending an entry's expiry on each successful
+// access. Each time Get or TryGet returns a Hit without an error, the
+// entry's expiry is reset to now + age. This is useless without MaxAge
+// or without setting MaxIdleAge to a positive duration.
```
Comment (weeco) [inline cache/cache.go]: Is this true? It seems maxIdleAge is used as the initial TTL if `MaxAge` is not set

Comment (twmb) [reply cache/cache.go]: Bad doc comment, logic in code is correct, will fix comment.

Comment (twmb) [reply cache/cache.go]: done
